config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    get "/edit_request", to: "bloods#edit_request", as: 'blood_edit_request'
    patch "/update_request", to: "bloods#update_request",  as: 'blood_update_request' 
    get "/edit_donation", to: "bloods#edit_donation", as: 'blood_edit_donation'
    patch "/update_donation", to: "bloods#update_donation",  as: 'blood_update_donation' 
    get "/stocks", to: "users#stocks", as: 'blood_stock'
    get "/user_request", to: "users#user_request", as: 'user_request'
    get "/admin_all_request", to: "users#admin_all_request", as: 'admin_all_request'
    patch "/update_accept_request", to: "allrequests#update_accept_request", as: 'update_accept_request'
    patch "/update_reject_request", to: "allrequests#update_reject_request", as: 'update_reject_request'
    get "/user_profile_page", to: "users#user_profile_page", as: 'user_profile_page'
    get "/admin_all_donations", to: "users#admin_all_donations", as: 'admin_all_donations'
    resources :bloods
  end

  root "bloods#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alldonation.rb
class Alldonation < ApplicationRecord
  belongs_to :user
end

app/models/allrequest.rb
class Allrequest < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood.rb
class Blood < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :alldonations, dependent: :destroy
  has_one :allrequest, dependent: :destroy
  
end

app/controllers/allrequests_controller.rb
class AllrequestsController < ApplicationController
    def update_accept_request
        
        @update_accept= User.find(params[:user_id])
        @update_accept.allrequest.update(status: "approved")
        redirect_to root_path
    end

    def update_reject_request
        @update_reject= User.find(params[:user_id])
        @update_reject.allrequest.update(status: "rejected")
        redirect_to root_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :number ,:email, :password, :isadmin, :address)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :number ,:email, :password, :current_password, :isadmin, :address)}
         end
end

app/controllers/bloods_controller.rb
class BloodsController < ApplicationController
    def index
        
    end

    def edit_request
        @blood_groups = Blood.where("unit > 0").pluck(:blood_group)
    end

    def edit_donation
    end

    def update_donation
        @donate= Blood.find_by(blood_group: params[:user][:blood_group])
        @donate.update(unit: @donate.unit + params[:user][:unit].to_i)
        @donation_histroy= Alldonation.create(user_id: current_user.id, blood_group_name: @donate.blood_group, unit: params[:user][:unit].to_i)
        redirect_to root_path
    end

    def update_request
        @request=Blood.find_by(blood_group: params[:user][:blood_group])
        @request.update(unit: @request.unit - 1)
        @request_history= Allrequest.create(user_id: current_user.id, reason: params[:user][:reason], blood_group_name: @request.blood_group)
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @all_donations=current_user.alldonations
    end

    def stocks
        @all_groups_details = Blood.all
    end

    def user_request
        @request= current_user.allrequest
    end

    def admin_all_request
        @all_users = User.all
    end

    def user_profile_page
        @user_details= User.find(params[:user_id])
    end

    def admin_all_donations
        @all_donations= User.all
    end
end

app/helpers/allrequests_helper.rb
module AllrequestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloods_helper.rb
module BloodsHelper
end

app/views/bloods/edit_donation.html.erb
<div class="donation-form">


    
    <%= form_with(model: current_user, url: user_blood_update_donation_path(current_user)) do |f| %> 
    
        <div>
            <%= f.label :blood_group, "Blood Group Type" %> 
            <%= f.select :blood_group, ["B+", "B-", "A+", "A-", "AB+", "AB-", "O+", "O-"] %> <br> <br>
        </div>
    
    
    
        <div>
            <%= f.label :unit, "Enter the Units for Donation" %>
            <%= f.number_field :unit, in: 1..20, step: 1 %> <br>
        </div>
    
        <div>
            <br />
            <%= f.submit "Donate" %>
            <br />
        </div>
    
    <% end %>
</div>

app/views/bloods/edit_request.html.erb
<div class="donation-form">

    <% if current_user.allrequest.present? %>
        <h1 style="text-align:center; padding:400px;">You Made a Request already for today. Come Back Tommorrow!! </h1>
    <% else %>
        <%= form_with(model: current_user, url: user_blood_update_request_path(current_user)) do |f| %> 
            <div>
                <%= f.label :blood_group, "Blood Group Type" %> 
                <%= f.select :blood_group, @blood_groups     %> <br> <br>
            </div>
            <div>
                <%= f.label :reason %>
                <%= f.text_area :reason %>
            </div>
    
            <div>
                <br />
                <%= f.submit "Request" %>
                <br />
            </div>
        <% end %>
    <% end %>
</div>

app/views/bloods/index.html.erb
<%= image_tag "homepage.jpg" , class: "homepage-image" %>

<p class="homepage-text">"Opportunites knock the door sometimes, so don't let it go and donate blood"
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloodManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? && current_user.isadmin %>
      <%= render 'partial/admin_navbar' %>
    <% else %>
      <%= render 'partial/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partial/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
      <%= link_to "BLOOD BANK WEBSITE", root_path, class: "navbar-brand text-white bg-dark h3" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <%= link_to "All Requests ", user_admin_all_request_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            
            <li class="nav-item">
                <%= link_to "All Donations History", user_admin_all_donations_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <% if current_user.allrequest.present? %>
                    <%= link_to "Your Request", user_user_request_path(current_user), class: "nav-link active text-white bg-dark h3" %>
                <% else %>
                    
                <% end  %>
            </li>
            <li class="nav-item">
                <%= link_to "Blood Stock", user_blood_stock_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            
            </ul>
        </div>
        <% end %>
    </div>
    <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item text-white bg-dark h3" %>
                </li>
            </ul>
        </div>

    <% end %>
  </nav>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
      <%= link_to "BLOOD BANK WEBSITE", root_path, class: "navbar-brand text-white bg-dark h3" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <%= link_to "Request", user_blood_edit_request_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <%= link_to "Donate", user_blood_edit_donation_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <%= link_to "All Donations History", user_path(current_user), class: "nav-link active text-white bg-dark h3" %>
            </li>
            <li class="nav-item">
                <% if current_user.allrequest.present? %>
                    <%= link_to "Your Request", user_user_request_path(current_user), class: "nav-link active text-white bg-dark h3" %>
                <% else %>
                    
                <% end  %>
            </li>
           
            </ul>
        </div>
        <% end %>
    </div>
    <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item text-white bg-dark h3" %>
                </li>
            </ul>
        </div>

    <% end %>
  </nav>

app/views/users/admin_all_donations.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
          font-size: 18px;
        }
        
        table {
          margin: 0 auto;
          border-collapse: collapse;
        }
        
        th, td {
          padding: 8px;
          text-align: center;
          border: 1px solid #ddd;
        }
        
        th {
          background-color: #f2f2f2;
          font-weight: bold;
        }
    </style>
</head>
<body>
    <% if Alldonation.count==0 %>
    <h1 style="text-align:center; padding:400px;">No Donations Found </h1>
    <% else %>
        <h1 style="font-size: 30px; text-align:center; padding:30px;">All Donations History </h1>
        <table>
            <thead>
                <tr>
                    <th> Name </th>    
                    <th> Blood Group Name </th>
                    <th> Unit </th>
                    <th> Date Time </th>
                </tr>
            </thead>
            <tbody>
                <% for i in @all_donations %>
                    <% if i.id == current_user.id %>
                    <% else %>
                        <% for j in i.alldonations %>  
                            <tr>
                                <td> <%= i.name %> </td>
                                <td>  <%= j.blood_group_name %>  </td>
                                <td>  <%= j.unit %> </td>
                                <td>  <%= j.created_at %> </td>
                            </tr>
                        <% end %>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    <% end %>
</body>
</html>

app/views/users/admin_all_request.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
          font-size: 18px;
        }
        
        table {
          margin: 0 auto;
          border-collapse: collapse;
        }
        
        th, td {
          padding: 8px;
          text-align: center;
          border: 1px solid #ddd;
        }
        
        th {
          background-color: #f2f2f2;
          font-weight: bold;
        }
    </style>
</head>
<body>
    <% if Allrequest.count==0 %>
        <h1 style="text-align:center; padding:400px;">No Requests Found </h1>
    <% else %>
        <% for i in @all_users %>
            <% if i.id != current_user.id %>
                <h1 style="font-size: 30px; text-align:center; padding:30px;">All Request</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Blood Group Name</th>
                            <th>Reason</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% for i in @all_users %>
                            <% if i.id != current_user.id %> 
                                <tr>
                                    <td>  <%= link_to User.find(i.id).name, user_user_profile_page_path(i.id), style:"text-decoration:none; color:inherit;" %>  </td>
                                    <td>  <%= User.find(i.id).allrequest.blood_group_name %> </td>
                                    <td>  <%= User.find(i.id).allrequest.reason %> </td>
                                    <% if User.find(i.id).allrequest.status=="pending" %>
                                        <td> <%= link_to "Accept", user_update_accept_request_path(i.id), method: :patch , class: "btn btn-primary" %> &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Reject", user_update_reject_request_path(i.id), method: :patch, class: "btn btn-danger" %> </td>
                                    <% else %>
                                        <td> <%= User.find(i.id).allrequest.status %> </td>
                                    <% end %>
                                </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            <% end %>
        <% end %>
    <% end %>
</body>

</html>

app/views/users/index.html.erb
<h1> Your Bloood Request </h1>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
          font-size: 18px;
        }
        
        table {
          margin: 0 auto;
          border-collapse: collapse;
        }
        
        th, td {
          padding: 8px;
          text-align: center;
          border: 1px solid #ddd;
        }
        
        th {
          background-color: #f2f2f2;
          font-weight: bold;
        }
    </style>
</head>
<body>
    <% if current_user.alldonations.count==0 %>
        <h1 style="text-align:center; padding:400px;">You didn't Donated Any Blood Unit </h1>
    <% else %>
        <h1 style="font-size: 30px; text-align:center; padding:30px;">All Donations History </h1>
        <table>
            <thead>
                <tr>
                    <th>Blood Group Name</th>
                    <th>Unit</th>
                    <th>Date Time</th>
                </tr>
            </thead>
            <tbody>
                <% for i in @all_donations %>  
                    <tr>
                        <td>  <%= i.blood_group_name %>  </td>
                        <td>  <%= i.unit %> </td>
                        <td>  <%= i.created_at %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
</body>
</html>

app/views/users/stocks.html.erb
<div class="stock-heading"> Blood Stock </div>
<div class="grid-container">
    <% @all_groups_details.each do |i| %>
      <div class="grid-item">
        <p><%= content_tag :p, i.blood_group, class: "grid-item-text" %> <%= i.unit %></p>
      </div>
    <% end %>
</div>

app/views/users/user_profile_page.html.erb
<h1 style="text-align: center; padding-top:100px; font-size:5px;">  </h1>
<div class="user-container">
    <div class="p1">Name </div> <div class="p2"> <%= @user_details.name %> </div> <br>
    <div class="p1">Mobile Number </div> <div class="p2"> <%= @user_details.number %></div> <br>
    <div class="p1">Address</div> <div class="p2"> <%= @user_details.address %></div> <br>
    <div class="p1">Email</div> <div class="p2"> <%= @user_details.email %></div>
    

     
</div>

app/views/users/user_request.html.erb
<h4 style="text-align: center; padding: 100px; font-size: 30px"> Your Request </h4>
<p style="text-align: center; padding:50px; font-size: 40px;">
    Blood Group Name :-  <%= @request.blood_group_name %> <br> <br>
    Reason :- <%= @request.reason %>. <br><br>
    Status :- <%= @request.status.capitalize %> <br>
</p>